[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https://code.getmdl.io https://fonts.googleapis.com https://fonts.gstatic.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' https://code.getmdl.io; style-src 'self' 'unsafe-inline' https://code.getmdl.io https://fonts.googleapis.com;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 